// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    Login: typeof import('./src/components/Login.vue')['default']
    NotebookList: typeof import('./src/components/NotebookList.vue')['default']
    NoteDetail: typeof import('./src/components/NoteDetail.vue')['default']
    NoteSidebar: typeof import('./src/components/NoteSidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    TrashDetail: typeof import('./src/components/TrashDetail.vue')['default']
  }
}
